### ISSUE TITLE
Unable to show keyboard on view after `.setText(null)` or `.setText("")` is called

### ISSUE THREAD

**Issue by privacy-unknown** [ChaosLeong/PinView#12] opened 2018-02-07 15:44 UTC
I'm using this view to receive PIN from user and if PIN is incorrect - pin field is must cleared and appropriate message is shown.
So when `pinView.setText(null);` method is called - i can't enter PIN again, because keyboard is not showed anymore (does not matter which cell is clicked).

**Comment by privacy-unknown** [comment] 2018-02-07 15:57
Hot-fix for this issue is to set Touch Listener and force to show keyboard up

`pinView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
                assert imm != null;
                imm.showSoftInput(pinView, InputMethodManager.SHOW_IMPLICIT);
                return false;
            }
        });`

**Comment by privacy-unknown** [comment] 2018-02-07 16:03
Proposed solution to fix it is to override  `performClick()` method in PinView and force to show keyboard, but not tested yet

**Comment by ChaosLeong** [comment] 2018-03-31 06:12
Hey @privacy-unknown , sorry for my late reply.

By doing make research on `EditText` and `TextView`, I found the root cause of the issue.

IMM will be marked to **can be opened** state by `spanChange` method in TextView, and the `spanChange` will only be invoked by `onSpanXXX` methods in `ChangeWatcher` (Defined in `TextView`).
The `PinView` override `getDefaultMovementMethod` and return `null`, it will causing the `onSpanXXX` methods not be invoked when setText. So the IMM cannot be opened after `.setText(null)` or `.setText("")`.

**Comment by ChaosLeong** [comment] 2018-03-31 06:16
I will fix this issue tomorrow

**Comment by ChaosLeong** [comment] 2018-04-02 01:32
The issue has been fixed in version 1.3.1.

**Closed by ChaosLeong** 2018-04-02 01:32 UTC
